package com.sportsequipment.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;
import lombok.Getter;
import lombok.Setter;

/**
 * 地址实体类
 * @author sports-equipment-team
 */
@Entity
@Table(name = "address")
@Getter
@Setter
public class Address {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The userId is now handled by the User relationship below

    @Column(nullable = false)
    @NotBlank(message = "Recipient name is required")
    @Size(max = 50, message = "Recipient name cannot exceed 50 characters")
    private String name;

    @Column(nullable = false)
    @NotBlank(message = "Phone number is required")
    @Size(max = 20, message = "Phone number cannot exceed 20 characters")
    private String phone;

    @Column(nullable = false)
    @NotBlank(message = "Address is required")
    @Size(max = 255, message = "Address cannot exceed 255 characters")
    private String address;

    @Column(name = "is_default")
    private boolean isDefault = false;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    // Relationships
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    private User user;
    
    // Remove the duplicate userId field since it's handled by the relationship
    // private Long userId; // This is now handled by the User relationship

    public Address() {
    }

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // Getters and setters are automatically generated by Lombok
    // Custom getter for boolean field isDefault to maintain standard naming convention
    public boolean isDefault() {
        return isDefault;
    }
}