package com.sportsequipment.entity;

import jakarta.persistence.*;
import java.util.List;
import lombok.Getter;
import lombok.Setter;

/**
 * 主分类实体类
 * @author sports-equipment-team
 */
@Entity
@Table(name = "main_category")
@Getter
@Setter
public class MainCategory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String name;

    private String description;

    @OneToMany(mappedBy = "mainCategory", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<SubCategory> subCategories;

    // Getters and setters are automatically generated by Lombok
}
    